version: '3.9'

services:
  app:
    build:
      dockerfile: ./Dockerfile-dev
      context: .
    ports:
      - ${APP_PORT}:${APP_PORT}
    command: sh -c "yarn start"
    volumes:
      - ./src:/opt/app/src
    environment:
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}

      APP_NAME: ${APP_NAME}
      APP_PORT: ${APP_PORT}

    depends_on:
      - database


  database:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MONGO_INITDB_DATABASE: ${DATABASE_NAME}
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME:  ${DATABASE_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD:  ${DATABASE_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/